# Stage 1: Build the React app
FROM node:14 AS build

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Stage 2: Serve the React app with Nginx
FROM nginx:alpine

# Copy the build output to the Nginx HTML directory
COPY --from=build /app/build /usr/share/nginx/html

# Copy a custom Nginx configuration file
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 85
EXPOSE 85

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]

# $ docker run -d -p 5000:5000 --name local-registry registry:2
# Verify the status of the container.

# $ docker container ls
# CONTAINER ID   IMAGE           COMMAND                     CREATED   STATUS                        PORTS             NAMES
# 5da2f5c25843   registry:2   "/entrypoint.sh /etc…"   7 minutes ago   Up 7 minutes   0.0.0.0:5000->5000/tcp   local-registry